---
title: "MA615 HW1 Formatting Exercise"
author: "Yichu Yan"
date: "9/19/2019"
output: pdf_document
header-includes:
- \usepackage{placeins}
- \usepackage{xcolor}
---

Extract from:
  
Bradley Efron and Trevor Hastie

\it Computer Age Statistical Inference: Algorithms, Evidence, and Data Science 

\it Cambridge University Press, 2016

\it https://web.stanford.edu/~hastie/CASI_files/PDF/casi.pdf \



Modern Bayesian practice uses various strategies to construct an appropriate “prior” g(${\mu}$)in the absence of prior experience, leaving many statisticians unconvinced by the resulting Bayesian inferences. Our second example illustrates the difficulty.  \



\textcolor[HTML]{06578D}{Table 3.1} Scores from two tests taken by 22 students, \textcolor[HTML]{013300}{mechanics} and \textcolor[HTML]{013300}{vectors}.


\begin{table}[!h]
\begin{center}
\begin{tabular}{llllllllllll}
                                 & 1  & 2  & 3  & 4  & 5  & 6  & 7  & 8  & 9  & 10 & 11 \\ \hline
{\color[HTML]{013300} mechanics} & 7  & 44 & 49 & 59 & 34 & 46 & 0  & 32 & 49 & 52 & 44 \\
{\color[HTML]{013300} vectors}  & 51 & 69 & 41 & 70 & 42 & 40 & 40 & 45 & 57 & 64 & 61 \\ \hline
                                &    &    &    &    &    &    &    &    &    &    &    \\ 
                                 & 12 & 13 & 14 & 15 & 16 & 17 & 18 & 19 & 20 & 21 & 22 \\ \hline
{\color[HTML]{013300} mechanics} & 36 & 42 & 5  & 22 & 18 & 41 & 48 & 31 & 42 & 46 & 63 \\
{\color[HTML]{013300} vectors}   & 59 & 60 & 30 & 58 & 51 & 63 & 38 & 42 & 69 & 49 & 63 \\ \hline
\end{tabular}
\end{center}
\end{table} \





Table 3.1 shows the scores on two tests, \textcolor[HTML]{013300}{mechanics} and \textcolor[HTML]{013300}{vectors}, achieved by n = 22 students. The sample correlation coefficient between the two scores is $\hat{\theta}$ = 0.498,  \


$\hat{\theta } =\sum_{i=1}^{22}\left (  m_{i} -\bar{m}\right)\left (  v_{i} -\bar{v}\right ) / \left ( \sum_{i=1}^{22}\left (  m_{i} -\bar{m}\right )^{2}\sum_{i=1}^{22}\left ( v_{i}- \bar{v}\right )^{2}\right )^{1/2}$  \



with m and v short for \textcolor[HTML]{013300}{mechanics} and \textcolor[HTML]{013300}{vectors}, $\bar{m}$ and $\bar{v}$ their averages.
